//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAllergy
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> AllergyID { get; set; }
    
        public virtual Allergy Allergy { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
