//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.ComplaintTestResults = new HashSet<ComplaintTestResult>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TestTypeID { get; set; }
        public Nullable<int> AdmittanceID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Result { get; set; }
        public Nullable<int> BodyRegionID { get; set; }
    
        public virtual Admittance Admittance { get; set; }
        public virtual BodyRegion BodyRegion { get; set; }
        public virtual ICollection<ComplaintTestResult> ComplaintTestResults { get; set; }
        public virtual TestType TestType { get; set; }
    }
}
