//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRole
    {
        public ChatRole()
        {
            this.ChatResponses = new HashSet<ChatRespons>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ChatRespons> ChatResponses { get; set; }
    }
}
