//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintTestResult
    {
        public int ID { get; set; }
        public Nullable<int> ComplaintID { get; set; }
        public Nullable<int> TestResultID { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual Test Test { get; set; }
    }
}
