//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public Complaint()
        {
            this.ComplaintTestResults = new HashSet<ComplaintTestResult>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AdmittanceID { get; set; }
        public string ComplaintTypeID { get; set; }
    
        public virtual Admittance Admittance { get; set; }
        public virtual ICollection<ComplaintTestResult> ComplaintTestResults { get; set; }
    }
}
