//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalDataEntities : DbContext
    {
        public MedicalDataEntities()
            : base("name=MedicalDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admittance> Admittances { get; set; }
        public DbSet<Allergy> Allergies { get; set; }
        public DbSet<BodyRegion> BodyRegions { get; set; }
        public DbSet<ChatRespons> ChatResponses { get; set; }
        public DbSet<ChatRole> ChatRoles { get; set; }
        public DbSet<ClinicalNote> ClinicalNotes { get; set; }
        public DbSet<ClinicalNoteType> ClinicalNoteTypes { get; set; }
        public DbSet<Complaint> Complaints { get; set; }
        public DbSet<ComplaintTestResult> ComplaintTestResults { get; set; }
        public DbSet<Med> Meds { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<PatientAllergy> PatientAllergies { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<StaffType> StaffTypes { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<TestCategory> TestCategories { get; set; }
        public DbSet<TestType> TestTypes { get; set; }
        public DbSet<Vital> Vitals { get; set; }
        public DbSet<VitalSignType> VitalSignTypes { get; set; }
    }
}
